### ISSUE TITLE
Where is Configuration?

### ISSUE THREAD

**Issue by a-sawatome** [AdamStelmaszczyk/learning2run#1]
We try to using your quickstart.py.
But we got the error said 'ImportError: cannot import name Configuration'.
In tensorforce package, we can not find 'Configuration' file.
Where is the Configuration file ?

**Comment by AdamStelmaszczyk** [comment]
This quickstart.py (from [here](http://tensorforce.readthedocs.io/en/latest/)) file is a leftover after connecting it osim-rl env to [TensorForce](https://github.com/reinforceio/tensorforce) TRPO. To make it work you need to install TensorForce. I removed this file (8240473114b79d980cd03cfc9d111751ae3d9872) from repo as it is not part of the solution, thanks for spotting this.

We finally went for PPO from [baselines](https://github.com/openai/baselines), they also have TRPO if you are interested.
