### ISSUE TITLE
TRPO result checking

### ISSUE THREAD

**Issue by anindyasarkarIITH** [AdamStelmaszczyk/learning2run#2]
How to check TRPO baseline on this current setup? can you please provide a guideline for this?

**Comment by AdamStelmaszczyk** [comment]
You should replace a call to PPO from baselines (https://github.com/AdamStelmaszczyk/learning2run/blob/master/run_osim.py#L130) to TRPO from baselines (https://github.com/AdamStelmaszczyk/learning2run/blob/master/baselines/baselines/trpo_mpi/trpo_mpi.py), leaving all the rest the same (remember to also use `preprocess` function in TRPO).

**Comment by anindyasarkarIITH** [comment]
Thanks for replying.I will try this out as you have mentioned.
